### ISSUE TITLE
Socket file creation?

### ISSUE THREAD

**Issue by dinshaw** [boxen/puppet-mysql#16]
to avoid the need to customize the database config, would it be possible/a good idea to do something like:
```
$ mysqladmin variables | grep socket
> /opt/boxen/data/mysql/socket
$ ln -s /opt/boxen/data/mysql/socket /tmp/mysql.sock
```
?
This worked for me on a Mt Lion install. This is my first dip into Puppet/Boxen, so sorry if i missed something obvious.

if it seems like a good approach, i will submit a PR

**Comment by seanknox** [comment]
I think this comes down to engineering teams determining the tools they use; if they decide to use Boxen or support developers using Boxen, it's not (IMO) much to provide Rails database configs (in the examples above) with support for Boxen or non-Boxen users.
