### ISSUE TITLE
OSX System Preferences MySQL pane doesn't work with Boxen install

### ISSUE THREAD

**Issue by wingamajig** [boxen/puppet-mysql#20]
The MySQL startup item & preference pane don't work with the Boxen MySQL install.

I was able to see the server status by adding a symlink to /usr/local like so:
lrwxr-xr-x  1 root  wheel   20 Jun 20 16:42 mysql -> /opt/boxen/homebrew/

However, the start/stop button is greyed out.

**Comment by seanknox** [comment]
I don't think this is an issue anymore—if not, feel free to reopen.
