### ISSUE TITLE
Can't connect to database as root without password

### ISSUE THREAD

**Issue by hidde-jan** [boxen/puppet-mysql#23]
Hi,

I've just added `puppet-mysql` to my boxen setup and things don't work out as planned. First, I was getting errors during installation. Now, it doesn't give any warnings, but when running with `--debug` I noticed the following error:

```
Debug: Exec[grant root user privileges](provider=shell): Executing check '/bin/sh-cmysql -u root -P 13306       -e "select * from mysql.user where User = 'root' and Host = 'localhost'"       --password='' | grep root'
Debug: Executing '/bin/sh -c mysql -u root -P 13306       -e "select * from mysql.user where User = 'root' and Host = 'localhost'"       --password='' | grep root'
Debug: /Stage[main]/Mysql/Exec[grant root user privileges]/unless: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
```

I've checked to see if mysql is running and it is. Trying to connect manually also fails:

```
$ mysql -uroot
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
```

Any idea what could be the cause of this?

**Comment by seanknox** [comment]
I don't think this is an issue anymore—if not, feel free to reopen.
