### ISSUE TITLE
Overwritable my.cnf Template

### ISSUE THREAD

**Issue by hughevans** [boxen/puppet-mysql#39]
Would it be a good idea to allow a custom `my.cnf.erb` in our-boxen? For example I want to add `sql_mode=STRICT_ALL_TABLES` to it and currently it seems as though I’d need to fork puppet-mysql to do this.

If it’s deemed to be a good idea, where would be a good location in the our-boxen tree? `./config`?

**Comment by seanknox** [comment]
As @rds13 points out, there are a variety of ways to overwrite configuration templates in Boxen/Puppet.
