### ISSUE TITLE
Readonly grants always executed

### ISSUE THREAD

**Issue by simpsora** [boxen/puppet-mysql#45]
... at least for me.

In `user/grant.pp`, the `exec` is guarded by the following `unless`:
```
unless  => "mysql -uroot -p13306 -e 'SHOW GRANTS FOR ${username}@'${host}';' \
--password='' | grep -w '${database}' | grep -w '${grants}'"
```

`${grants}` is ```$grants = 'SELECT, LOCK TABLES, CREATE TEMPORARY TABLES'```

On my machine, running the `unless` clause manually returns the grants in a different order than specified in `${grants}`:
```
$ mysql -uroot -p13306 -e 'SHOW GRANTS FOR dbuser@'localhost'' --password='' | grep -w 'dev_db'
GRANT SELECT, CREATE TEMPORARY TABLES, LOCK TABLES ON `dev_db`.* TO 'dbuser'@'localhost'
```

This causes the `unless` to fail, and the grant is always executed.  
It'd be nice if this didn't happen, but I can't think of an elegant solution.

**Comment by mikemcquaid** [comment]
Should be fixed as-of https://github.com/boxen/puppet-mysql/pull/51, 1.99.92. I assume MySQL just changed the order these are returned. If not we'll try another approach.
