### ISSUE TITLE
MySQL URL and mirror both broken links

### ISSUE THREAD

**Issue by ericathegreat** [boxen/puppet-mysql#71]
The main URL for MySQL is dead (320), and the Sourceforge mirror link is redirecting to an interstitial page now.

https://github.com/boxen/puppet-mysql/blob/master/files/brews/mysql.rb

I couldn't find the new 'correct' URLs. Sorry!

**Comment by ericathegreat** [comment]
Found the correct main link:
https://dev.mysql.com/get/Downloads/MySQL-5.6/mysql-5.6.25.tar.gz

**Comment by rypit** [comment]
@ericathegreat nice find with the 5.6.25 link! Please also see #69 and #70 -- they both include updated versions of MySQL
